CREATE TYPE ROLETYPE AS ENUM ('ADMIN', 'MODERATOR', 'GUEST');

CREATE TABLE IF NOT EXISTS members(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role ROLETYPE NOT NULL,
    user_id UUID NOT NULL,
    server_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);